/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.transfer.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.docs.transfer.model.Transfer;
import com.liferay.docs.transfer.model.TransferModel;
import com.liferay.docs.transfer.model.TransferSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Transfer service. Represents a row in the &quot;GB_Transfer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TransferModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransferImpl}.
 * </p>
 *
 * @author liferay
 * @see TransferImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TransferModelImpl
	extends BaseModelImpl<Transfer> implements TransferModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transfer model instance should use the <code>Transfer</code> interface instead.
	 */
	public static final String TABLE_NAME = "GB_Transfer";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"transferId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("transferId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GB_Transfer (uuid_ VARCHAR(75) null,transferId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table GB_Transfer";

	public static final String ORDER_BY_JPQL =
		" ORDER BY transfer.transferId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GB_Transfer.transferId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.transfer.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.docs.transfer.model.Transfer"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.transfer.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.docs.transfer.model.Transfer"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.transfer.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.docs.transfer.model.Transfer"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long TRANSFERID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Transfer toModel(TransferSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Transfer model = new TransferImpl();

		model.setUuid(soapModel.getUuid());
		model.setTransferId(soapModel.getTransferId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Transfer> toModels(TransferSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Transfer> models = new ArrayList<Transfer>(soapModels.length);

		for (TransferSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.docs.transfer.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.docs.transfer.model.Transfer"));

	public TransferModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _transferId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTransferId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _transferId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Transfer.class;
	}

	@Override
	public String getModelClassName() {
		return Transfer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Transfer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Transfer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Transfer, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Transfer)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Transfer, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Transfer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Transfer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Transfer, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Transfer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Transfer>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Transfer.class.getClassLoader(), Transfer.class,
			ModelWrapper.class);

		try {
			Constructor<Transfer> constructor =
				(Constructor<Transfer>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Transfer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Transfer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Transfer, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Transfer, Object>>();
		Map<String, BiConsumer<Transfer, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Transfer, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object uuid) {
					transfer.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"transferId",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getTransferId();
				}

			});
		attributeSetterBiConsumers.put(
			"transferId",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object transferId) {
					transfer.setTransferId((Long)transferId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object groupId) {
					transfer.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object companyId) {
					transfer.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object userId) {
					transfer.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object userName) {
					transfer.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object createDate) {
					transfer.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object modifiedDate) {
					transfer.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object status) {
					transfer.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object statusByUserId) {
					transfer.setStatusByUserId((Long)statusByUserId);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object statusByUserName) {
					transfer.setStatusByUserName((String)statusByUserName);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object statusDate) {
					transfer.setStatusDate((Date)statusDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<Transfer, Object>() {

				@Override
				public Object apply(Transfer transfer) {
					return transfer.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<Transfer, Object>() {

				@Override
				public void accept(Transfer transfer, Object name) {
					transfer.setName((String)name);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTransferId() {
		return _transferId;
	}

	@Override
	public void setTransferId(long transferId) {
		_transferId = transferId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Transfer.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Transfer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Transfer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Transfer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TransferImpl transferImpl = new TransferImpl();

		transferImpl.setUuid(getUuid());
		transferImpl.setTransferId(getTransferId());
		transferImpl.setGroupId(getGroupId());
		transferImpl.setCompanyId(getCompanyId());
		transferImpl.setUserId(getUserId());
		transferImpl.setUserName(getUserName());
		transferImpl.setCreateDate(getCreateDate());
		transferImpl.setModifiedDate(getModifiedDate());
		transferImpl.setStatus(getStatus());
		transferImpl.setStatusByUserId(getStatusByUserId());
		transferImpl.setStatusByUserName(getStatusByUserName());
		transferImpl.setStatusDate(getStatusDate());
		transferImpl.setName(getName());

		transferImpl.resetOriginalValues();

		return transferImpl;
	}

	@Override
	public int compareTo(Transfer transfer) {
		long primaryKey = transfer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Transfer)) {
			return false;
		}

		Transfer transfer = (Transfer)obj;

		long primaryKey = transfer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TransferModelImpl transferModelImpl = this;

		transferModelImpl._originalUuid = transferModelImpl._uuid;

		transferModelImpl._originalGroupId = transferModelImpl._groupId;

		transferModelImpl._setOriginalGroupId = false;

		transferModelImpl._originalCompanyId = transferModelImpl._companyId;

		transferModelImpl._setOriginalCompanyId = false;

		transferModelImpl._setModifiedDate = false;

		transferModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Transfer> toCacheModel() {
		TransferCacheModel transferCacheModel = new TransferCacheModel();

		transferCacheModel.uuid = getUuid();

		String uuid = transferCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			transferCacheModel.uuid = null;
		}

		transferCacheModel.transferId = getTransferId();

		transferCacheModel.groupId = getGroupId();

		transferCacheModel.companyId = getCompanyId();

		transferCacheModel.userId = getUserId();

		transferCacheModel.userName = getUserName();

		String userName = transferCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			transferCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			transferCacheModel.createDate = createDate.getTime();
		}
		else {
			transferCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			transferCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			transferCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		transferCacheModel.status = getStatus();

		transferCacheModel.statusByUserId = getStatusByUserId();

		transferCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = transferCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			transferCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			transferCacheModel.statusDate = statusDate.getTime();
		}
		else {
			transferCacheModel.statusDate = Long.MIN_VALUE;
		}

		transferCacheModel.name = getName();

		String name = transferCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			transferCacheModel.name = null;
		}

		return transferCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Transfer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Transfer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Transfer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Transfer)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Transfer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Transfer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Transfer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Transfer)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Transfer>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _transferId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _name;
	private long _columnBitmask;
	private Transfer _escapedModel;

}